GET http://localhost:3000/categories

###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "game",
    "description": "Articles related to game"
}

###

PATCH http://localhost:3000/categories/20
Content-Type: application/json

{
    "name": "games",
    "description": "Articles related to games"
}

###

DELETE http://localhost:3000/categories/28
Content-Type: application/json


